# envioWhatsapp.py
import pywhatkit
import pyautogui
import pyperclip
import datetime
import ctypes
import time
import subprocess
import os
import logging

from mensajes.mensajeCotizacionesDolar import generar_cotizacion_dolar
from mensajes.mensajeResumen import generar_mensaje_resumen
from mensajes.mensajeAlertaCompra import generar_alerta_aleatoria
from mensajes.mensajeAlertaCompraArg import generar_alerta_aleatoria_arg
from registros.reporteAlertas import generar_resumen_alertas, seleccionar_y_copiar_excel

# NUEVO: configuramos el log para guardar los eventos en un archivo
logging.basicConfig(
    filename="C:\\Users\\Tomas\\OneDrive\\Escritorio\\impulso_wsp_bot\\log_envioWhatsapp.log",
    level=logging.INFO,
    format='%(asctime)s %(message)s'
)

ES_CONTINUOUS = 0x80000000
ES_SYSTEM_REQUIRED = 0x00000001
ES_AWAYMODE_REQUIRED = 0x00000040

ctypes.windll.kernel32.SetThreadExecutionState(ES_CONTINUOUS | ES_SYSTEM_REQUIRED | ES_AWAYMODE_REQUIRED)

nombre_grupo = "LDHlzsldWl2B03bfRnVNA9" #Grupo Impulso
# nombre_grupo = "EfwcuD1Yj9QC7nHQSN9TdT" #Grupo Revisión

mensajes_semana = [
    {"dias": ["monday", "tuesday", "wednesday", "thursday", "friday"], "hora": "08:50", "mensaje": "noticia_mercado"},
    {"dias": ["monday", "tuesday", "wednesday", "thursday", "friday"], "hora": "11:00", "mensaje": "resumenAlertas", "grupo": "EfwcuD1Yj9QC7nHQSN9TdT"},
    {"dias": ["monday", "tuesday", "wednesday", "thursday", "friday"], "hora": "11:03", "mensaje": "alerta_bursatil", "grupo": "EfwcuD1Yj9QC7nHQSN9TdT"},
    {"dias": ["monday", "tuesday", "wednesday", "thursday", "friday"], "hora": "11:06", "mensaje": "alerta_bursatil", "grupo": "EfwcuD1Yj9QC7nHQSN9TdT"},
    {"dias": ["monday", "tuesday", "wednesday", "thursday", "friday"], "hora": "11:09", "mensaje": "alerta_bursatil_arg", "grupo": "EfwcuD1Yj9QC7nHQSN9TdT"},
    {"dias": ["monday", "tuesday", "wednesday", "thursday", "friday"], "hora": "11:12", "mensaje": "alerta_bursatil_arg", "grupo": "EfwcuD1Yj9QC7nHQSN9TdT"},
    {"dias": ["monday", "tuesday", "wednesday", "thursday", "friday"], "hora": "15:00", "mensaje": "cotizacion_dolar"},
    {"dias": ["friday"], "hora": "13:30", "mensaje": "💰 *¡No te olvides de caucionar lo líquido este finde semana!*"},
    # {"dias": ["tuesday"], "hora": "00:30", "mensaje": "💰 *¡No te olvides de caucionar lo líquido este finde semana!*", "grupo": "EfwcuD1Yj9QC7nHQSN9TdT"}, #TEST
]

mensajes_fecha = [
    {"fecha": "13/06/2025 12:20", "mensaje": "📢 *Aviso Feriado:*\n" "El lunes 16/06 la Bolsa de Buenos Aires estará cerrada por el feriado en conmemoración del Gral. Güemes."},
    {"fecha": "18/06/2025 12:20", "mensaje": "📢 *Aviso Feriado:*\n" "El jueves 19/06 la Bolsa de Nueva York estará cerrada por Juneteenth.\nEl viernes 20/06 la Bolsa de Buenos Aires estará cerrada por el Paso a la Inmortalidad del Gral.  Belgrano."},
    {"fecha": "02/07/2025 12:20", "mensaje": "📢 *Aviso Feriado:*\n" "El jueves 03/07 la Bolsa de Nueva York cerrará temprano a las 13:00 por el Día de Independencia.\nEl viernes 04/07 estará cerrada por el mismo motivo."},
    {"fecha": "08/07/2025 12:20", "mensaje": "📢 *Aviso Feriado:*\n" "El lunes 09/06 la Bolsa de Buenos Aires estará cerrada por el feriado del Día de la Independencia."},
    {"fecha": "14/08/2025 12:20", "mensaje": "📢 *Aviso Feriado:*\n" "El lunes 15/08 la Bolsa de Buenos Aires estará cerrada por el feriado en honor al Gral. San Martín."},
    {"fecha": "29/08/2025 12:20", "mensaje": "📢 *Aviso Feriado:*\n" "El lunes 01/09 la Bolsa de Nueva York estará cerrada por el feriado del Día del Trabajo."},
    {"fecha": "20/11/2025 12:20", "mensaje": "📢 *Aviso Feriado:*\n" "El viernes 21/11 y el lunes 24/11 la Bolsa de Buenos Aires estará cerrada por el feriado del Día de la Soberanía Nacional."},
    {"fecha": "26/11/2025 12:20", "mensaje": "📢 *Aviso Feriado:*\n" "El jueves 27/11 la Bolsa de Nueva York estará cerrada por el Día de Acción de Gracias.\nEl viernes 28/11 cerrará temprano a las 13:00 por el mismo motivo."},
    {"fecha": "05/12/2025 12:20", "mensaje": "📢 *Aviso Feriado:*\n" "El lunes 08/12 la Bolsa de Buenos Aires estará cerrada por el feriado de la Inmaculada Concepción."},
    {"fecha": "23/12/2025 12:20", "mensaje": "📢 *Aviso Feriado:*\n" "El martes 24/12 la Bolsa de Nueva York cerrará temprano a las 13:00 hs por la víspera de Navidad.\n""El miércoles 25/12 Las Bolsas de Nueva York y Buenos Aires permanecerán cerradas por el feriado de Navidad."},
    {"fecha": "19/06/2025 12:30", "mensaje": "📢 *Vencimiento de Opciones*\n📅 Mañana, viernes 20/06, se produce el vencimiento mensual de opciones.\n⚠️ Recuerde que pueden negociarse hasta hoy (jueves 19/06) a las 15:30 hs y ejercerse en cualquier momento."},
    {"fecha": "17/07/2025 12:30", "mensaje": "📢 *Vencimiento de Opciones*\n📅 Mañana, viernes 18/07, se produce el vencimiento mensual de opciones.\n⚠️ Recuerde que pueden negociarse hasta hoy (jueves 17/07) a las 15:30 hs y ejercerse en cualquier momento."},
    {"fecha": "14/08/2025 12:30", "mensaje": "📢 *Vencimiento de Opciones*\n📅 Mañana, viernes 15/08, se produce el vencimiento mensual de opciones.\n⚠️ Recuerde que pueden negociarse hasta hoy (jueves 14/08) a las 15:30 hs y ejercerse en cualquier momento."},
    {"fecha": "18/09/2025 12:30", "mensaje": "📢 *Vencimiento de Opciones*\n📅 Mañana, viernes 19/09, se produce el vencimiento mensual de opciones.\n⚠️ Recuerde que pueden negociarse hasta hoy (jueves 18/09) a las 15:30 hs y ejercerse en cualquier momento."}, 
    {"fecha": "16/10/2025 12:30", "mensaje": "📢 *Vencimiento de Opciones*\n📅 Mañana, viernes 17/10, se produce el vencimiento mensual de opciones.\n⚠️ Recuerde que pueden negociarse hasta hoy (jueves 16/10) a las 15:30 hs y ejercerse en cualquier momento."},
    {"fecha": "20/11/2025 12:30", "mensaje": "📢 *Vencimiento de Opciones*\n📅 Mañana, viernes 21/11, se produce el vencimiento mensual de opciones.\n⚠️ Recuerde que pueden negociarse hasta hoy (jueves 20/11) a las 15:30 hs y ejercerse en cualquier momento."},
    {"fecha": "18/12/2025 12:30", "mensaje": "📢 *Vencimiento de Opciones*\n📅 Mañana, viernes 19/12, se produce el vencimiento mensual de opciones.\n⚠️ Recuerde que pueden negociarse hasta hoy (jueves 18/12) a las 15:30 hs y ejercerse en cualquier momento."},
    {"fecha": "15/01/2026 12:30", "mensaje": "📢 *Vencimiento de Opciones*\n📅 Mañana, viernes 16/01, se produce el vencimiento mensual de opciones.\n⚠️ Recuerde que pueden negociarse hasta hoy (jueves 15/01) a las 15:30 hs y ejercerse en cualquier momento."},
    {"fecha": "19/02/2026 12:30", "mensaje": "📢 *Vencimiento de Opciones*\n📅 Mañana, viernes 20/02, se produce el vencimiento mensual de opciones.\n⚠️ Recuerde que pueden negociarse hasta hoy (jueves 19/02) a las 15:30 hs y ejercerse en cualquier momento."},
    {"fecha": "19/03/2026 12:30", "mensaje": "📢 *Vencimiento de Opciones*\n📅 Mañana, viernes 20/03, se produce el vencimiento mensual de opciones.\n⚠️ Recuerde que pueden negociarse hasta hoy (jueves 19/03) a las 15:30 hs y ejercerse en cualquier momento."},
    {"fecha": "16/04/2026 12:30", "mensaje": "📢 *Vencimiento de Opciones*\n📅 Mañana, viernes 17/04, se produce el vencimiento mensual de opciones.\n⚠️ Recuerde que pueden negociarse hasta hoy (jueves 16/04) a las 15:30 hs y ejercerse en cualquier momento."},
    {"fecha": "14/05/2026 12:30", "mensaje": "📢 *Vencimiento de Opciones*\n📅 Mañana, viernes 15/05, se produce el vencimiento mensual de opciones.\n⚠️ Recuerde que pueden negociarse hasta hoy (jueves 14/05) a las 15:30 hs y ejercerse en cualquier momento."},
    {"fecha": "18/06/2026 12:30", "mensaje": "📢 *Vencimiento de Opciones*\n📅 Mañana, viernes 19/06, se produce el vencimiento mensual de opciones.\n⚠️ Recuerde que pueden negociarse hasta hoy (jueves 18/06) a las 15:30 hs y ejercerse en cualquier momento."},
    {"fecha": "16/07/2026 12:30", "mensaje": "📢 *Vencimiento de Opciones*\n📅 Mañana, viernes 17/07, se produce el vencimiento mensual de opciones.\n⚠️ Recuerde que pueden negociarse hasta hoy (jueves 16/07) a las 15:30 hs y ejercerse en cualquier momento."},
    {"fecha": "20/08/2026 12:30", "mensaje": "📢 *Vencimiento de Opciones*\n📅 Mañana, viernes 21/08, se produce el vencimiento mensual de opciones.\n⚠️ Recuerde que pueden negociarse hasta hoy (jueves 20/08) a las 15:30 hs y ejercerse en cualquier momento."},
    {"fecha": "17/09/2026 12:30", "mensaje": "📢 *Vencimiento de Opciones*\n📅 Mañana, viernes 18/09, se produce el vencimiento mensual de opciones.\n⚠️ Recuerde que pueden negociarse hasta hoy (jueves 17/09) a las 15:30 hs y ejercerse en cualquier momento."},
    {"fecha": "15/10/2026 12:30", "mensaje": "📢 *Vencimiento de Opciones*\n📅 Mañana, viernes 16/10, se produce el vencimiento mensual de opciones.\n⚠️ Recuerde que pueden negociarse hasta hoy (jueves 15/10) a las 15:30 hs y ejercerse en cualquier momento."},
    {"fecha": "19/11/2026 12:30", "mensaje": "📢 *Vencimiento de Opciones*\n📅 Mañana, viernes 20/11, se produce el vencimiento mensual de opciones.\n⚠️ Recuerde que pueden negociarse hasta hoy (jueves 19/11) a las 15:30 hs y ejercerse en cualquier momento."},
    {"fecha": "17/12/2026 12:30", "mensaje": "📢 *Vencimiento de Opciones*\n📅 Mañana, viernes 18/12, se produce el vencimiento mensual de opciones.\n⚠️ Recuerde que pueden negociarse hasta hoy (jueves 17/12) a las 15:30 hs y ejercerse en cualquier momento."},
    {"fecha": "14/01/2027 12:30", "mensaje": "📢 *Vencimiento de Opciones*\n📅 Mañana, viernes 15/01, se produce el vencimiento mensual de opciones.\n⚠️ Recuerde que pueden negociarse hasta hoy (jueves 14/01) a las 15:30 hs y ejercerse en cualquier momento."},
    {"fecha": "18/02/2027 12:30", "mensaje": "📢 *Vencimiento de Opciones*\n📅 Mañana, viernes 19/02, se produce el vencimiento mensual de opciones.\n⚠️ Recuerde que pueden negociarse hasta hoy (jueves 18/02) a las 15:30 hs y ejercerse en cualquier momento."},
    {"fecha": "18/03/2027 12:30", "mensaje": "📢 *Vencimiento de Opciones*\n📅 Mañana, viernes 19/03, se produce el vencimiento mensual de opciones.\n⚠️ Recuerde que pueden negociarse hasta hoy (jueves 18/03) a las 15:30 hs y ejercerse en cualquier momento."},
    {"fecha": "15/04/2027 12:30", "mensaje": "📢 *Vencimiento de Opciones*\n📅 Mañana, viernes 16/04, se produce el vencimiento mensual de opciones.\n⚠️ Recuerde que pueden negociarse hasta hoy (jueves 15/04) a las 15:30 hs y ejercerse en cualquier momento."},
    {"fecha": "20/05/2027 12:30", "mensaje": "📢 *Vencimiento de Opciones*\n📅 Mañana, viernes 21/05, se produce el vencimiento mensual de opciones.\n⚠️ Recuerde que pueden negociarse hasta hoy (jueves 20/05) a las 15:30 hs y ejercerse en cualquier momento."},
    {"fecha": "11/06/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es un ETF?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 *¿Qué es un ETF?*\nEs un fondo que agrupa muchas acciones o activos (como el S&P 500, bonos, materias primas, etc.) y se compra como si fuera una acción individual.\n\n✅ *Permiten invertir en índices, sectores o regiones*\n✅ *Tienen baja comisión y alta liquidez*\n✅ *Podés acceder a una cartera diversificada en una sola operación*\n✅ *Se operan como cualquier acción, en tiempo real*\n\n📊 *Ideal para diversificar y seguir una estrategia sin elegir activos uno por uno.*"},
    {"fecha": "18/06/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es la tasa de interés?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es la tasa de interés?\nEs el porcentaje que se paga por prestar dinero o el rendimiento que genera una inversión.\n\n✅ Afecta préstamos, ahorros e inversiones\n✅ Una tasa alta puede incentivar el ahorro y encarecer créditos\n✅ Una tasa baja puede estimular el consumo y la inversión\n✅ Clave para entender cómo funciona la economía\n\n*📊 Ideal para saber cómo impacta en tus finanzas personales e inversiones.*"},
    {"fecha": "25/06/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es un bono?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es un bono?\nEs un título de deuda que emite un gobierno o empresa para pedir plata prestada y, a cambio, paga intereses periódicos.\n\n✅ Recibís pagos de interés fijos o variables\n✅ Al vencimiento, te devuelven el capital invertido\n✅ Son una opción más segura que las acciones\n✅ Se usan para diversificar y generar ingresos estables\n\n*📊 Ideal para quienes buscan menor riesgo y rendimientos predecibles.*"},
    {"fecha": "02/07/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es la diversificación?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es la diversificación?\nEs repartir tus inversiones en diferentes activos para reducir riesgos.\n\n✅ No poner todos los huevos en la misma canasta\n✅ Protege tu dinero de caídas fuertes en un activo\n✅ Mejora la estabilidad y el rendimiento a largo plazo\n✅ Clave para una estrategia de inversión segura\n\n*📊 Ideal para minimizar riesgos y maximizar oportunidades.*"},
    {"fecha": "09/07/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es un fondo mutuo?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es un fondo mutuo?\nEs un vehículo de inversión donde muchas personas juntan su dinero para invertir en conjunto en acciones, bonos u otros activos.\n\n✅ Administrado por profesionales que eligen las mejores inversiones\n✅ Permite diversificar incluso con poco dinero\n✅ Es más accesible y menos riesgoso que invertir solo\n✅ Podés comprar y vender participaciones fácilmente\n\n*📊 Ideal para quienes quieren invertir sin preocuparse por elegir activos específicos.*"},
    {"fecha": "16/07/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es un índice bursátil?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es un índice bursátil?\nEs un indicador que agrupa un conjunto de acciones representativas de un mercado o sector (como el S&P 500 o el Merval) para medir su comportamiento general.\n\n✅ Permite ver cómo va el mercado en general\n✅ Sirve para comparar el rendimiento de tus inversiones\n✅ Se usa como referencia para fondos y ETFs\n✅ Facilita invertir en todo un mercado sin elegir acciones específicas\n\n*📊 Ideal para entender la salud del mercado y diversificar con un solo instrumento.*"},
    {"fecha": "23/07/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es el riesgo financiero?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es el riesgo financiero?\nEs la posibilidad de perder dinero o no obtener la ganancia esperada en una inversión.\n\n✅ Puede deberse a cambios en el mercado, economía o empresa\n✅ Cada inversión tiene un nivel distinto de riesgo\n✅ Entenderlo ayuda a tomar decisiones más inteligentes\n✅ Se maneja diversificando y eligiendo inversiones adecuadas\n\n*📊 Ideal para proteger tu dinero y evitar sorpresas desagradables.*"},
    {"fecha": "30/07/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es la volatilidad?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es la volatilidad?\nEs la medida de cuánto varía el precio de un activo en un período de tiempo.\n\n✅ Alta volatilidad significa cambios rápidos y grandes en el precio\n✅ Baja volatilidad indica precios más estables\n✅ Influye en el riesgo de la inversión\n✅ Entenderla ayuda a manejar mejor tus emociones y decisiones\n\n*📊 Ideal para saber qué esperar y elegir inversiones según tu perfil.*"},
    {"fecha": "06/08/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es la liquidez?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es la liquidez?\nEs la facilidad y rapidez con la que podés convertir una inversión en efectivo sin perder valor.\n\n✅ Alta liquidez significa que podés vender rápido y sin problemas\n✅ Baja liquidez puede implicar demora o pérdida al vender\n✅ Importante para tener dinero disponible cuando lo necesites\n✅ Afecta la elección de tus inversiones según tus objetivos\n\n*📊 Ideal para manejar bien tu dinero y evitar quedar atrapado en inversiones difíciles de vender.*"},
    {"fecha": "13/08/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es un dividendo?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es un dividendo?\nEs la parte de las ganancias que una empresa reparte a sus accionistas como recompensa por invertir.\n\n✅ Pueden ser pagos en efectivo o más acciones\n✅ Son una forma de obtener ingresos pasivos\n✅ No todas las empresas pagan dividendos\n✅ Se suelen repartir periódicamente (trimestral, anual)\n\n*📊 Ideal para quienes buscan ingresos adicionales sin vender sus acciones.*"},
    {"fecha": "20/08/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué son las acciones blue chips?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué son las acciones blue chips?\nSon acciones de empresas grandes, reconocidas y sólidas, con buena reputación y estabilidad financiera.\n\n✅ Suelen tener menor riesgo que otras acciones\n✅ Pagán dividendos regulares\n✅ Son líderes en su sector y mercado\n✅ Ideal para inversores que buscan estabilidad y crecimiento seguro\n\n*📊 Perfectas para armar una cartera sólida y confiable.*"},
    {"fecha": "27/08/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es el apalancamiento?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es el apalancamiento?\nEs usar dinero prestado para aumentar el monto que invertís, buscando multiplicar ganancias, pero también aumentando riesgos.\n\n✅ Permite invertir más de lo que tenés\n✅ Puede amplificar tanto ganancias como pérdidas\n✅ Requiere manejo cuidadoso para evitar grandes pérdidas\n✅ Se usa mucho en inversiones y trading\n\n*📊 Ideal para quienes entienden bien los riesgos y buscan potenciar sus inversiones.*"},
    {"fecha": "03/09/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es una IPO (Oferta Pública Inicial)?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es una IPO?\nEs la primera vez que una empresa ofrece sus acciones al público para financiar su crecimiento y convertirse en una compañía pública.\n\n✅ Permite a la empresa conseguir capital para expandirse\n✅ Los inversores pueden comprar acciones desde el inicio\n✅ Es una oportunidad para participar en empresas nuevas y en crecimiento\n✅ Implica riesgos porque la empresa es nueva en bolsa\n\n*📊 Ideal para quienes quieren invertir en etapas tempranas de empresas.*"},
    {"fecha": "10/09/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es un activo financiero?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es un activo financiero?\nEs un recurso que representa dinero o derecho a recibir dinero, como acciones, bonos o efectivo.\n\n✅ Generan ingresos o ganancias potenciales\n✅ Se pueden comprar, vender o intercambiar\n✅ Son la base para invertir y crecer tu patrimonio\n✅ Cada tipo tiene características y riesgos distintos\n\n*📊 Ideal para entender qué estás comprando cuando invertís.*"},
    {"fecha": "17/09/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es la capitalización de mercado?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es la capitalización de mercado?\nEs el valor total de todas las acciones de una empresa en el mercado, calculado multiplicando el precio de la acción por la cantidad de acciones emitidas.\n\n✅ Indica el tamaño y peso de una empresa\n✅ Se usa para clasificar empresas en grandes, medianas o pequeñas\n✅ Ayuda a evaluar riesgos y oportunidades\n✅ Es un dato clave para inversores y analistas\n\n*📊 Ideal para entender la escala de una empresa y comparar inversiones.*"},
    {"fecha": "24/09/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es un split de acciones?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es un split de acciones?\nEs cuando una empresa divide sus acciones existentes en más unidades, reduciendo el precio por acción pero sin cambiar el valor total de la inversión.\n\n✅ Hace que las acciones sean más accesibles para pequeños inversores\n✅ No cambia el valor total que tenés invertido\n✅ Puede aumentar la liquidez de la acción\n✅ Se usa para mejorar el atractivo de la acción en el mercado\n\n*📊 Ideal para facilitar la compra y venta de acciones.*"},
    {"fecha": "01/10/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es el costo promedio ponderado (promedio de compra)?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es el costo promedio ponderado?\nEs el precio promedio al que compraste un activo, considerando todas las compras que hiciste y la cantidad adquirida en cada una.\n\n✅ Te ayuda a saber cuánto pagaste realmente por acción o bono\n✅ Útil para calcular ganancias o pérdidas\n✅ Facilita decisiones para comprar o vender\n✅ Es una estrategia para reducir el impacto de la volatilidad\n\n*📊 Ideal para tener claridad y controlar mejor tus inversiones.*"},
    {"fecha": "08/10/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es un stop loss?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es un stop loss?\nEs una orden que ponés para vender una acción automáticamente cuando su precio baja a un nivel que definiste, para limitar pérdidas.\n\n✅ Ayuda a proteger tu dinero de caídas grandes\n✅ Es una herramienta clave para manejar riesgos\n✅ Se usa mucho en trading e inversiones\n✅ Permite operar sin estar todo el tiempo pendiente del mercado\n\n*📊 Ideal para cuidar tu capital y evitar decisiones emocionales.*"},
    {"fecha": "15/10/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es el margen de seguridad en inversión?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es el margen de seguridad?\nEs la diferencia entre el valor real de una inversión y su precio de compra, que te protege contra errores o imprevistos.\n\n✅ Te ayuda a minimizar riesgos\n✅ Permite comprar con descuento respecto al valor real\n✅ Es un principio clave para inversores prudentes\n✅ Aumenta las probabilidades de ganar a largo plazo\n\n*📊 Ideal para tomar decisiones más seguras y confiables.*"},
    {"fecha": "22/10/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es la gestión pasiva vs gestión activa?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es la gestión pasiva?\nInvertir replicando un índice o mercado, sin hacer cambios frecuentes.\n\n🔹 ¿Qué es la gestión activa?\nBuscar superar al mercado seleccionando activos y haciendo cambios frecuentes.\n\n✅ Gestión pasiva: costos bajos y menos esfuerzo\n✅ Gestión activa: busca mayores ganancias pero con más riesgos y costos\n✅ Cada una tiene ventajas según el perfil del inversor\n✅ Importante entender para elegir tu estrategia\n\n*📊 Ideal para definir cómo querés manejar tus inversiones.*"},
    {"fecha": "29/10/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es la beta en finanzas?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es la beta?\nEs una medida que indica cuánto se mueve el precio de una acción en relación al mercado.\n\n✅ Beta mayor a 1: acción más volátil que el mercado\n✅ Beta menor a 1: acción menos volátil que el mercado\n✅ Beta igual a 1: se mueve igual que el mercado\n✅ Ayuda a evaluar el riesgo relativo de una acción\n\n*📊 Ideal para entender cómo puede variar tu inversión.*"},
    {"fecha": "05/11/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es el cash flow (flujo de caja)?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es el cash flow?\nEs la cantidad de dinero que entra y sale de una empresa en un periodo determinado.\n\n✅ Muestra la salud financiera real de la empresa\n✅ Importante para saber si puede pagar deudas y crecer\n✅ No es lo mismo que ganancias contables\n✅ Clave para evaluar inversiones en empresas\n\n*📊 Ideal para entender cómo circula el dinero en las compañías donde invertís.*"},
    {"fecha": "12/11/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es la deuda pública?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es la deuda pública?\nEs el dinero que el Estado pide prestado para financiar gastos y proyectos, pagando con intereses a los que le prestan.\n\n✅ Se financia con bonos y otros instrumentos\n✅ Es clave para mantener servicios y desarrollo\n✅ Puede afectar la economía y la inflación\n✅ Los inversores pueden comprar bonos públicos\n\n*📊 Ideal para entender cómo funciona la economía y las inversiones en bonos del Estado.*"},
    {"fecha": "19/11/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es la prima de riesgo?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es la prima de riesgo?\nEs la compensación extra que un inversor pide por asumir un riesgo mayor al invertir en un activo más riesgoso.\n\n✅ Se mide como diferencia entre el rendimiento esperado y el de un activo sin riesgo\n✅ Indica cuánto te pagan por correr riesgos adicionales\n✅ Ayuda a decidir si vale la pena invertir en activos más riesgosos\n✅ Importante para valorar bonos, acciones y proyectos\n\n*📊 Ideal para entender cuánto riesgo estás asumiendo y cómo te compensan por ello.*"},
    {"fecha": "26/11/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es un ETF inverso o apalancado?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es un ETF inverso?\nEs un fondo que busca ganar cuando el mercado baja, invirtiendo en la dirección contraria.\n\n🔹 ¿Qué es un ETF apalancado?\nEs un fondo que usa deuda para multiplicar las ganancias (y pérdidas) en relación al mercado.\n\n✅ Ambos son instrumentos avanzados\n✅ Tienen más riesgo y volatilidad\n✅ Requieren conocimientos y seguimiento constante\n✅ No son recomendados para principiantes\n\n*📊 Ideal para entender riesgos si querés explorar inversiones más complejas.*"},
    {"fecha": "03/12/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es el spread en la bolsa?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es el spread?\nEs la diferencia entre el precio de compra y el precio de venta de una acción o activo.\n\n✅ Indica el costo oculto de comprar y vender\n✅ Cuanto más pequeño, más fácil es negociar\n✅ Afecta la liquidez del mercado\n✅ Importante para entender costos y rentabilidad\n\n*📊 Ideal para optimizar tus operaciones y reducir gastos.*"},
    {"fecha": "10/12/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es la cartera de crecimiento vs la cartera conservadora?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es una cartera de crecimiento?\nBusca maximizar ganancias con inversiones más arriesgadas y volátiles.\n\n🔹 ¿Qué es una cartera conservadora?\nPrioriza proteger el capital con inversiones más seguras y estables.\n\n✅ Cartera de crecimiento: más riesgo, mayor potencial de ganancia\n✅ Cartera conservadora: menos riesgo, menor volatilidad\n✅ Elegir depende de tu perfil y objetivos\n✅ Balancear ambas puede ser una buena estrategia\n\n*📊 Ideal para definir cómo querés manejar tus inversiones según tu tolerancia al riesgo.*"},
    {"fecha": "17/12/2025 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es el ratio precio/utilidad (P/U)?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es el ratio P/U?\nEs una medida que compara el precio de una acción con las ganancias que genera por acción.\n\n✅ Un P/U alto puede indicar expectativas de crecimiento\n✅ Un P/U bajo puede sugerir que la acción está barata o en problemas\n✅ Útil para comparar empresas dentro de un sector\n✅ Ayuda a tomar decisiones de compra o venta\n\n*📊 Ideal para evaluar si una acción está sobrevaluada o subvaluada.*"},
    {"fecha": "07/01/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es una acción?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una *explicación breve y clave* 👇\n\n🔹 *¿Qué es una acción?*\n*Es una parte de propiedad de una empresa* que podés comprar y vender en la bolsa.\n\n✅ *Ser dueño de una acción significa ser socio de la empresa*\n✅ *Podés ganar plata si la empresa crece y su valor sube*\n✅ *Algunas acciones pagan dividendos* (ganancias distribuidas)\n✅ *Se negocian en mercados organizados* y su precio varía según oferta y demanda\n\n*📊 Ideal para quienes buscan crecimiento y participar en el éxito de las empresas.*"},
    {"fecha": "14/01/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es una cartera de inversión?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es una cartera de inversión?\nEs el conjunto de activos financieros que una persona tiene para diversificar y balancear riesgos y ganancias.\n\n✅ Combina acciones, bonos, fondos y otros activos\n✅ Ayuda a equilibrar rentabilidad y seguridad\n✅ Se ajusta según tus objetivos y perfil de riesgo\n✅ Clave para gestionar tu dinero de forma inteligente\n\n*📊 Ideal para construir un camino sólido hacia tus metas financieras.*"},
    {"fecha": "21/01/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es el trading vs la inversión?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué es el trading?\nComprar y vender activos en plazos cortos para aprovechar movimientos rápidos de precios.\n\n🔹 ¿Qué es la inversión?\nComprar activos para mantenerlos a largo plazo buscando crecimiento y ganancias sostenidas.\n\n✅ Trading: más riesgo y necesidad de estar atento\n✅ Inversión: enfoque en objetivos a largo plazo\n✅ Cada uno tiene su lugar según perfil y tiempo disponible\n✅ Es importante elegir lo que mejor se adapte a vos\n\n*📊 Ideal para entender cómo manejar tu dinero según tus objetivos.*"},
    {"fecha": "28/01/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué son los derivados financieros?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 ¿Qué son los derivados financieros?\nSon contratos cuyo valor depende del precio de otro activo, como acciones, bonos o materias primas.\n\n✅ Se usan para protegerse contra riesgos o para especular\n✅ Incluyen opciones, futuros y swaps\n✅ Pueden aumentar ganancias pero también pérdidas\n✅ Son instrumentos avanzados que requieren conocimiento\n\n*📊 Ideal para quienes quieren gestionar riesgos o diversificar estrategias.*"},
    {"fecha": "04/02/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es el Dollar-Cost Averaging (DCA)?*\n\nHola Impulsores! Como todos los miércoles, les dejamos una explicación breve y clave 👇\n\n🔹 *¿Qué es el DCA?*\nEs la estrategia de invertir la misma cantidad de dinero a intervalos regulares, sin importar el precio del activo.\n\n✅ Reduce el impacto de la volatilidad\n✅ Ayuda a evitar comprar todo en el peor momento\n✅ Fomenta la disciplina y el ahorro sistemático\n✅ Ideal para quienes recién comienzan y quieren constancia\n\n📊 *Ideal para construir posición sin estrés por el “precio perfecto”.*"},
    {"fecha": "11/02/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es el interés compuesto?*\n\nHola Impulsores! Explicación breve y clave 👇\n\n🔹 *Interés compuesto*\nEs el interés que se calcula sobre el capital **y** los intereses ya generados.\n\n✅ Hace que tu dinero crezca exponencialmente con el tiempo\n✅ Cuanto antes empieces, mayor efecto tiene\n✅ Requiere reinvertir las ganancias en lugar de retirarlas\n✅ Es el “motor” detrás de grandes patrimonios a largo plazo\n\n📊 *Ideal para entender por qué la constancia paga dividendos.*"},
    {"fecha": "18/02/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es el rendimiento al vencimiento (YTM)?*\n\nHola Impulsores! Explicación breve y clave 👇\n\n🔹 *YTM o TIR de un bono*\nEs la tasa anual que obtendrías si comprás el bono hoy y lo mantenés hasta el vencimiento, reinvirtiendo cupones.\n\n✅ Resume precio, cupones y plazo en un solo número\n✅ Permite comparar bonos distintos\n✅ Cuanto menor el precio, mayor el YTM (si todo lo demás se mantiene)\n✅ Útil para evaluar si conviene comprar o no\n\n📊 *Ideal para medir la rentabilidad real de un bono.*"},
    {"fecha": "25/02/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es la duración de un bono?*\n\nHola Impulsores! Explicación breve y clave 👇\n\n🔹 *Duración*\nMide en años la sensibilidad del precio de un bono ante cambios de tasas.\n\n✅ Duración alta = precio más sensible\n✅ Ayuda a estimar el riesgo de tasa\n✅ Permite armar carteras “defensivas” o “agresivas” en renta fija\n✅ No es lo mismo que plazo al vencimiento\n\n📊 *Ideal para controlar el riesgo de tus bonos cuando suben las tasas.*"},
    {"fecha": "04/03/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es el rebalanceo de cartera?*\n\nHola Impulsores! Explicación breve y clave 👇\n\n🔹 *Rebalancear*\nEs volver a tu distribución objetivo (ej. 60 % acciones / 40 % bonos) vendiendo lo que subió y comprando lo que bajó.\n\n✅ Mantiene tu riesgo bajo control\n✅ Obliga a vender caro y comprar barato\n✅ Puede hacerse trimestral, semestral o anual\n✅ Evita que una clase de activo domine la cartera\n\n📊 *Ideal para mantener disciplina y riesgo coherente con tu perfil.*"},
    {"fecha": "11/03/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es el horizonte de inversión?*\n\nHola Impulsores! Explicación breve y clave 👇\n\n🔹 *Horizonte de inversión*\nEs el tiempo que planeás mantener tu dinero invertido antes de usarlo.\n\n✅ Define qué activos convienen (acciones vs bonos, etc.)\n✅ A mayor horizonte, más tolerancia a la volatilidad\n✅ Clave para alinear riesgo y objetivos\n✅ Cambia con tus metas (casa, jubilación, viaje, etc.)\n\n📊 *Ideal para elegir productos acordes a tu momento de vida.*"},
    {"fecha": "18/03/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es el ratio precio/valor libro (P/B)?*\n\nHola Impulsores! Explicación breve y clave 👇\n\n🔹 *P/B*\nCompara el precio de mercado de la acción con su valor contable (“libro”).\n\n✅ P/B < 1 puede indicar infravaloración (o problemas)\n✅ P/B alto suele verse en empresas de alto crecimiento\n✅ Útil para sectores con activos tangibles (bancos, industriales)\n✅ Siempre combiná con otros ratios\n\n📊 *Ideal para detectar empresas baratas o caras respecto a su patrimonio.*"},
    {"fecha": "25/03/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: Small Caps vs Large Caps*\n\nHola Impulsores! Explicación breve y clave 👇\n\n🔹 *Small Caps*\nEmpresas de baja capitalización: más crecimiento posible, más volatilidad.\n\n🔹 *Large Caps*\nEmpresas grandes y consolidadas: menor riesgo, crecimiento moderado.\n\n✅ Diversificar entre ambas balancea riesgo-retorno\n✅ Small = potencia; Large = estabilidad\n✅ El ciclo económico influye en cuál rinde mejor\n\n📊 *Ideal para ajustar tu cartera según perfil y etapa del mercado.*"},
    {"fecha": "01/04/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: Sectores defensivos vs cíclicos*\n\nHola Impulsores! Explicación breve y clave 👇\n\n🔹 *Sectores defensivos*\nConsumo básico, salud, utilities: demandados incluso en crisis.\n\n🔹 *Sectores cíclicos*\nEnergía, autos, turismo: reaccionan al ciclo económico.\n\n✅ Defensivos protegen en recesión\n✅ Cíclicos potencian ganancias en expansión\n✅ Combinar ambos reduce sobresaltos\n\n📊 *Ideal para rotar tu cartera según la fase económica.*"},
    {"fecha": "08/04/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es el ciclo económico?*\n\nHola Impulsores! Explicación breve y clave 👇\n\n🔹 *Ciclo económico*\nSerie de fases: expansión, pico, recesión, valle y recuperación.\n\n✅ Influye en empleo, consumo e inversiones\n✅ Cada fase favorece distintos activos (bonos, acciones, materias primas)\n✅ Seguir indicadores (PIB, desempleo, tasas) ayuda a anticipar\n✅ No se puede predecir con exactitud, pero sí preparar\n\n📊 *Ideal para entender por qué los mercados suben y bajan.*"},
    {"fecha": "15/04/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: Bull Market vs Bear Market*\n\nHola Impulsores! Explicación breve y clave 👇\n\n🔹 *Bull Market*\nMercado en tendencia alcista prolongada (+20 %).\n\n🔹 *Bear Market*\nCaída prolongada (–20 % desde máximos).\n\n✅ Cambian estrategias: en bull se busca crecimiento; en bear, protección\n✅ La historia muestra que los bull duran más que los bear\n✅ Mantener el plan evita vender en pánico\n\n📊 *Ideal para ajustar expectativas sin dejarte llevar por el ánimo del mercado.*"},
    {"fecha": "22/04/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: Indicador RSI (Índice de Fuerza Relativa)*\n\nHola Impulsores! Explicación breve y clave 👇\n\n🔹 *RSI*\nOscilador que mide la velocidad de los cambios de precio (0-100).\n\n✅ >70 indica sobrecompra; <30 sobreventa (posibles giros)\n✅ Útil para timing, no para fundamentos\n✅ Funciona mejor en rangos laterales\n✅ Combinalo con tendencia y volumen\n\n📊 *Ideal para decidir entradas/salidas más técnicas.*"},
    {"fecha": "29/04/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es la inversión ESG?*\n\nHola Impulsores! Explicación breve y clave 👇\n\n🔹 *ESG*\nCriterios Ambientales, Sociales y de Gobernanza al elegir empresas.\n\n✅ Premia compañías sostenibles y éticas\n✅ Puede reducir riesgos regulatorios y reputacionales\n✅ Gana peso en fondos globales\n✅ No sacrifica rentabilidad a largo plazo si se hace bien\n\n📊 *Ideal para invertir alineado a tus valores y tendencias futuras.*"},
    {"fecha": "06/05/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué son las criptomonedas?*\n\nHola Impulsores! Explicación breve y clave 👇\n\n🔹 *Criptomonedas*\nActivos digitales basados en blockchain (ej. Bitcoin, Ethereum).\n\n✅ Descentralización y transacciones globales 24/7\n✅ Alta volatilidad y riesgo\n✅ Sirven para diversificar, especular o transferir valor\n✅ Requieren billeteras y seguridad extra\n\n📊 *Ideal para quienes buscan exposición a la revolución digital financiera.*"},
    {"fecha": "13/05/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es una stablecoin?*\n\nHola Impulsores! Explicación breve y clave 👇\n\n🔹 *Stablecoin*\nCriptomoneda vinculada 1:1 a un activo estable (dólar, oro) para reducir volatilidad.\n\n✅ Útil para resguardar valor en cripto\n✅ Facilita mover dinero entre exchanges\n✅ Riesgos dependen de la reserva y la regulación\n✅ Ejemplo: USDC, USDT, DAI\n\n📊 *Ideal para “parquear” ganancias sin salir del ecosistema cripto.*"},
    {"fecha": "20/05/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es el staking?*\n\nHola Impulsores! Explicación breve y clave 👇\n\n🔹 *Staking*\nBloquear criptomonedas para validar transacciones y ganar recompensas.\n\n✅ Genera ingresos pasivos en cripto\n✅ Implica riesgo de precio y de red\n✅ Necesita elegir proyectos confiables\n✅ Similar a “interés” pero descentralizado\n\n📊 *Ideal para rentabilizar criptos que pensás mantener a largo plazo.*"},
    {"fecha": "27/05/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es la tokenización de activos?*\n\nHola Impulsores! Explicación breve y clave 👇\n\n🔹 *Tokenización*\nConvertir derechos sobre un activo (inmueble, obra de arte, bono) en tokens digitales.\n\n✅ Permite fraccionar inversiones grandes\n✅ Aumenta liquidez y acceso global\n✅ Depende de marcos legales y plataformas seguras\n✅ Podría revolucionar mercados de capitales\n\n📊 *Ideal para diversificar en activos reales con poco capital.*"},
    {"fecha": "03/06/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es el Valor Presente Neto (VPN)?*\n\nHola Impulsores! Explicación breve y clave 👇\n\n🔹 *VPN*\nSuma los flujos de caja futuros descontados a hoy, menos la inversión inicial.\n\n✅ Si el VPN es positivo, el proyecto crea valor\n✅ Compara alternativas de inversión\n✅ Sensible a la tasa de descuento\n✅ Muy usado en finanzas corporativas\n\n📊 *Ideal para evaluar inversiones de largo plazo o proyectos propios.*"},
    {"fecha": "10/06/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es la Tasa Interna de Retorno (TIR)?*\n\nHola Impulsores! Explicación breve y clave 👇\n\n🔹 *TIR*\nEs la tasa que iguala el VPN a cero; en otras palabras, el rendimiento anual del proyecto.\n\n✅ Si la TIR supera tu costo de capital, conviene invertir\n✅ Útil para comparar proyectos de distinta escala\n✅ Puede tener múltiples valores si hay flujos irregulares\n✅ Complementa al VPN para decisiones robustas\n\n📊 *Ideal para medir la rentabilidad real de tus emprendimientos.*"},
    {"fecha": "17/06/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: Cobertura con opciones (Covered Call)*\n\nHola Impulsores! Explicación breve y clave 👇\n\n🔹 *Covered Call*\nVender opciones de compra sobre acciones que ya tenés.\n\n✅ Genera ingresos extra (prima)\n✅ Limita la ganancia si la acción sube mucho\n✅ Reduce ligeramente el riesgo de caída\n✅ Estrategia simple dentro de las opciones\n\n📊 *Ideal para rentabilizar carteras que pensás mantener.*"},
    {"fecha": "24/06/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es un Stop Gain (Take Profit)?*\n\nHola Impulsores! Explicación breve y clave 👇\n\n🔹 *Stop Gain*\nOrden automática para vender cuando el precio sube a tu objetivo.\n\n✅ Asegura ganancias antes de posibles retrocesos\n✅ Elimina la tentación de “esperar un poco más”\n✅ Complementa al stop loss para gestionar riesgo/beneficio\n✅ Debe ajustarse según volatilidad y objetivos\n\n📊 *Ideal para disciplina y cierre ordenado de operaciones ganadoras.*"},
    {"fecha": "01/07/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es el riesgo inflacionario?*\n\nHola Impulsores! Explicación breve y clave 👇\n\n🔹 *Riesgo inflacionario*\nPosibilidad de que la inflación erosione el poder de compra de tus inversiones.\n\n✅ Afecta más a instrumentos en pesos fijos\n✅ Protegerse con activos reales, bonos CER o dólares\n✅ Revisar rentabilidad *real* (descontar inflación)\n✅ Clave en economías volátiles como la nuestra\n\n📊 *Ideal para no confundir ganancia nominal con ganancia real.*"},
    {"fecha": "08/07/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es el riesgo político?*\n\nHola Impulsores! Explicación breve y clave 👇\n\n🔹 *Riesgo político*\nImpacto de cambios de gobierno, regulaciones o conflictos en los mercados.\n\n✅ Puede alterar reglas de juego y flujos de capital\n✅ Se mitiga diversificando países y monedas\n✅ Afecta especialmente a emergentes\n✅ Seguir noticias y calendario electoral ayuda a anticipar\n\n📊 *Ideal para entender por qué los precios se mueven ante elecciones o reformas.*"},
    {"fecha": "15/07/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: ¿Qué es la rotación de sectores?*\n\nHola Impulsores! Explicación breve y clave 👇\n\n🔹 *Rotación sectorial*\nMover inversiones de un sector a otro según el ciclo económico.\n\n✅ Potencia rendimientos aprovechando tendencias\n✅ Requiere monitorear datos macro y resultados corporativos\n✅ Puede hacerse vía ETFs sectoriales\n✅ Reduce la dependencia de un solo sector\n\n📊 *Ideal para dar dinamismo a tu cartera sin asumir riesgo excesivo.*"},
    {"fecha": "22/07/2026 15:30", "mensaje": "📚 *Miércoles de educación financiera*\n🧠 *Mini clase: Diversificación geográfica*\n\nHola Impulsores! Explicación breve y clave 👇\n\n🔹 *Diversificación geográfica*\nInvertir en distintos países y regiones.\n\n✅ Reduce riesgos locales (políticos, económicos)\n✅ Captura crecimiento de diferentes zonas\n✅ Se logra con CEDEARs, ETFs globales o fondos internacionales\n✅ Equilibra la cartera ante eventos específicos de un país\n\n📊 *Ideal para no depender solo de la economía argentina.*"},
    {"fecha": "06/06/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué significa cuando dicen que un bono está 'rindiendo el 20%'?\"\n\n🧠 *Respuesta Impulso Merval:*\nCuando se dice que un bono rinde 20%, significa que si lo comprás hoy y lo mantenés hasta el vencimiento, vas a ganar un 20% anual sobre lo que pagaste.\nEse rendimiento tiene en cuenta cuánto pagás hoy vs. cuánto te devuelve el bono (intereses y capital). No es lo mismo que la tasa que paga el bono originalmente, sino cuánto ganás en relación al precio actual.\n\n📊 *Tip:* A veces, un bono puede tener una tasa baja pero estar muy barato, y ahí es donde el rendimiento se dispara."},
    {"fecha": "13/06/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Conviene más comprar dólar MEP o dejar la plata en cauciones?\"\n\n🧠 *Respuesta Impulso Merval:*\nDepende del contexto. Las cauciones suelen dar una tasa diaria en pesos, y sirven para aprovechar la plata sin riesgo en el corto plazo. Si el dólar MEP está tranquilo y tenés pesos que no vas a usar, puede tener sentido dejarlos en caución unos días.\nAhora, si esperás que el dólar suba fuerte o querés cobertura, el MEP es una mejor opción, aunque a veces la diferencia se paga en el spread.\n\n📊 *Tip:* Una buena práctica es comparar la tasa mensual de la caución con la expectativa de devaluación. Si esperás que el dólar suba más que lo que rinde la caución, mejor cubrirte."},
    {"fecha": "20/06/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Por qué baja el precio de un bono aunque paga intereses?\"\n\n🧠 *Respuesta Impulso Merval:*\nQue un bono pague intereses no garantiza que suba de precio. Su valor depende de muchos factores: la tasa de interés del mercado, el riesgo del emisor, la inflación esperada y la demanda de ese bono. Si suben las tasas, los bonos existentes que pagan menos se vuelven menos atractivos y su precio baja.\nTambién puede pasar que el mercado perciba más riesgo (como un posible default), y eso impacta en el precio aunque siga pagando intereses.\n\n📊 *Tip:* A veces un bono puede tener buena renta pero caer de precio por condiciones externas. Por eso es clave mirar el contexto y no solo el cupón."},
    {"fecha": "27/06/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Cuándo conviene más comprar: antes o después del pago de dividendos?\"\n\n🧠 *Respuesta Impulso Merval:*\nSi comprás antes, cobrás el dividendo pero el precio suele caer después del pago.\nSi comprás después, evitás esa caída pero no cobrás dividendos.\n\n📊 *Tip:* Pensá en tu estrategia: ingreso por dividendos o ganancia por precio."},
    {"fecha": "04/07/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Por qué un bono puede pagar 50% anual pero igual ser riesgoso?\"\n\n🧠 *Respuesta Impulso Merval:*\nUn bono que paga un interés muy alto suele tener ese rendimiento porque el mercado percibe un riesgo elevado de impago o incumplimiento. Es como una ‘prima por riesgo’: cuanto más riesgoso, más paga para compensar.\nSi la empresa o país emisora tiene problemas económicos, puede no pagar intereses o capital a tiempo.\n\n📊 *Tip:* No te fijes solo en la tasa, fijate en el emisor y su salud financiera antes de invertir."},
    {"fecha": "11/07/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Por qué a veces sube el dólar y también suben los bonos?\"\n\n🧠 *Respuesta Impulso Merval:*\nAunque parezca contradictorio, puede pasar cuando hay expectativas de mejoras económicas o arreglos con el FMI que impulsan la confianza. El dólar sube por demanda o inflación, pero los bonos suben porque mejora la percepción del riesgo y el mercado anticipa pagos más seguros.\n\n📊 *Tip:* Observá siempre el contexto macro: dólar y bonos pueden reaccionar a factores diferentes o al mismo tiempo por distintos motivos."},
    {"fecha": "18/07/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Me conviene entrar a un bono si ya subió mucho?\"\n\n🧠 *Respuesta Impulso Merval:*\nEntrar después de una suba fuerte puede ser riesgoso porque el precio ya incorporó buena parte de las buenas noticias. Eso puede reducir tu potencial de ganancia o aumentar el riesgo de caída.\n\n📊 *Tip:* Antes de comprar, evaluá el rendimiento actual, la situación del emisor y el contexto económico. A veces es mejor esperar una corrección o buscar bonos con mejor precio."},
    {"fecha": "25/07/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué significa cuando dicen que una acción 'rompió resistencia'?\"\n\n🧠 *Respuesta Impulso Merval:*\nRomper una resistencia significa que el precio de la acción superó un nivel donde antes había tenido dificultad para subir. Esto suele indicar que hay más fuerza compradora y puede anticipar una suba mayor.\n\n📊 *Tip:* En análisis técnico, las resistencias actúan como ‘techo’. Que se rompa una resistencia es una señal positiva, pero siempre hay que confirmar con volumen y contexto."},
    {"fecha": "01/08/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Si vendo antes del pago de dividendos, lo cobro igual?\"\n\n🧠 *Respuesta Impulso Merval:*\nNo, para cobrar dividendos tenés que ser dueño de la acción en la fecha de corte o ‘ex-dividendo’. Si vendés antes de esa fecha, el comprador es quien recibe el pago.\n\n📊 *Tip:* Revisá siempre la fecha ex-dividendo para planificar tus ventas y cobros."},
    {"fecha": "08/08/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Por qué un bono a descuento puede rendir más que uno que paga mucho cupón?\"\n\n🧠 *Respuesta Impulso Merval:*\nUn bono a descuento se compra por menos de su valor nominal y al vencimiento paga el total. La diferencia entre lo que pagás y lo que recibís genera rendimiento, que puede superar al de bonos con cupones altos si el precio de compra es suficientemente bajo.\n\n📊 *Tip:* No solo fijes en el cupón, también mirá el precio y el plazo para calcular el rendimiento total."},
    {"fecha": "15/08/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Conviene reinvertir las cauciones todos los días o dejarlo una semana?\"\n\n🧠 *Respuesta Impulso Merval:*\nLa caución semanal suele ofrecer una mejor tasa que los plazos más cortos o más largos, por eso suele ser nuestra recomendación.\nReinvertir a diario puede aprovechar el interés compuesto, pero implica más operaciones y seguimiento.\n\n📊 *Tip:* Revisá comisiones y tu disponibilidad. Si podés dejarlo una semana, es una opción simple y rentable."},
    {"fecha": "22/08/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué diferencia hay entre una ON en pesos y una en dólares?\"\n\n🧠 *Respuesta Impulso Merval:*\nUna ON (Obligación Negociable) en pesos paga intereses y capital en pesos, por lo que está expuesta a la inflación y tipo de cambio.\nUna ON en dólares paga en dólares, ofreciendo protección frente a la devaluación, pero puede tener más riesgo cambiario para argentinos.\n\n📊 *Tip:* Elegí según tu estrategia y expectativa del dólar y la inflación."},
    {"fecha": "29/08/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué significa cuando una acción está 'planchada'?\"\n\n🧠 *Respuesta Impulso Merval:*\nUna acción está 'planchada' cuando su precio se mueve muy poco, casi sin volatilidad, generalmente porque hay poca demanda o el mercado está esperando novedades.\n\n📊 *Tip:* En estos casos, suele ser difícil aprovechar movimientos rápidos, pero también puede ser oportunidad si esperás una noticia que la haga subir."},
    {"fecha": "05/09/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Es mejor comprar una acción que está subiendo o esperar una baja?\"\n\n🧠 *Respuesta Impulso Merval:*\nNo hay respuesta única. Comprar en suba puede aprovechar momentum, pero el precio puede estar alto.\nEsperar una baja puede conseguir mejor precio, pero el mercado puede seguir subiendo.\n\n📊 *Tip:* Definí tu estrategia y tolerancia al riesgo. El timing perfecto es difícil; lo importante es invertir con disciplina y objetivos claros."},
    {"fecha": "12/09/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué implica vender con stop loss? ¿Pierdo mucha plata?\"\n\n🧠 *Respuesta Impulso Merval:*\nVender con stop loss es poner un límite automático para vender si el precio baja hasta cierto nivel, para evitar pérdidas mayores.\nNo siempre pierdes mucha plata, depende de dónde pongas ese límite.\n\n📊 *Tip:* Usar stop loss ayuda a controlar el riesgo y emociones, pero debe estar bien calibrado para no vender por caídas temporarias."},
    {"fecha": "19/09/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Me conviene pasar de plazo fijo a dólar MEP?\"\n\n🧠 *Respuesta Impulso Merval:*\nDepende de tus objetivos: si buscás protegerte de la inflación y la devaluación, el dólar MEP puede ser mejor a largo plazo.\nSi priorizás una ganancia fija en pesos o lo necesitas en pesos dentro de un periodo corto de tiempo, el plazo fijo es mejor opción.\n\n📊 *Tip:* Considerá tu horizonte y tolerancia al riesgo antes de mover la plata."},
    {"fecha": "26/09/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué significa cuando dicen que un bono es 'duro'?\"\n\n🧠 *Respuesta Impulso Merval:*\nUn bono ‘duro’ es uno que tiene vencimiento a largo plazo, por lo general más de 10 años. Esto implica mayor riesgo por tiempo, pero también puede ofrecer mejores rendimientos.\n\n📊 *Tip:* Los bonos duros suelen ser más sensibles a cambios en tasas e inflación."},
    {"fecha": "03/10/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Si compro un CEDEAR, influye la cotización del dólar CCL?\"\n\n🧠 *Respuesta Impulso Merval:*\nSí, porque los CEDEAR reflejan acciones extranjeras pero se negocian en pesos, y el dólar CCL es el que se usa para transferir dólares entre mercados.\nSi el dólar CCL sube, el precio en pesos del CEDEAR suele subir también.\n\n📊 *Tip:* Para invertir en CEDEAR, seguí siempre el dólar CCL y las noticias del mercado internacional."},
    {"fecha": "10/10/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué quiere decir que un bono esté operando 'con ley extranjera'?\"\n\n🧠 *Respuesta Impulso Merval:*\nSignifica que el bono está emitido bajo la legislación de otro país (ejemplo: Nueva York) en vez de la argentina.\nEsto brinda mayor protección legal al inversor y puede facilitar pagos en moneda extranjera.\n\n📊 *Tip:* Los bonos con ley extranjera suelen ser más confiables para inversores, pero pueden tener riesgos legales distintos y tener un rendimiento menor."},
    {"fecha": "17/10/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Por qué si baja la tasa en EE.UU. suben los CEDEARs?\"\n\n🧠 *Respuesta Impulso Merval:*\nCuando bajan las tasas en EE.UU., los costos de financiamiento son menores y la rentabilidad de activos seguros baja, haciendo que los inversores busquen más acciones y CEDEARs, subiendo su precio.\n\n📊 *Tip:* Las tasas impactan mucho en la valoración de activos, por eso los CEDEARs suelen subir cuando las tasas bajan."},
    {"fecha": "24/10/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué hago si compré un bono largo y necesito la plata antes?\"\n\n🧠 *Respuesta Impulso Merval:*\nPodés vender el bono en el mercado antes del vencimiento, pero su precio puede ser menor o mayor al que pagaste, dependiendo de las tasas y el mercado.\n\n📊 *Tip:* Evaluá siempre el precio de mercado y tus necesidades. Vender antes puede generar ganancias o pérdidas."},
    {"fecha": "31/10/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué implica que un bono tenga duration 6 años? ¿Es malo si sube la tasa?\"\n\n🧠 *Respuesta Impulso Merval:*\nLa duration mide cuánto tarda en recuperarse el dinero invertido y cuánto puede cambiar el precio del bono si suben las tasas.\nUn bono con duration 6 años es sensible a cambios en tasas: si suben, su precio puede caer bastante.\n\n📊 *Tip:* Cuanto mayor la duration, mayor el riesgo ante suba de tasas, pero también mayor potencial de ganancia si bajan."},
    {"fecha": "07/11/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Cómo saber si un bono tiene riesgo de default?\"\n\n🧠 *Respuesta Impulso Merval:*\nEl riesgo de default es la posibilidad de que el emisor no pague intereses o capital a tiempo.\nPara evaluarlo, mirá la calificación crediticia, la situación financiera del emisor y el contexto económico.\n\n📊 *Tip:* Las agencias de rating y análisis de mercado son buenas fuentes para medir este riesgo."},
    {"fecha": "14/11/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Por qué me recomiendan esperar al rebote para vender?\"\n\n🧠 *Respuesta Impulso Merval:*\nEsperar al rebote significa vender cuando el precio se recupera un poco tras una caída, para no concretar pérdidas mayores.\nAsí podés aprovechar una mejor cotización y proteger tu inversión.\n\n📊 *Tip:* Ten paciencia y usa análisis técnico para identificar buenos momentos de venta."},
    {"fecha": "21/11/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Cuándo conviene rotar la cartera?\"\n\n🧠 *Respuesta Impulso Merval:*\nConviene rotar la cartera cuando cambian las condiciones del mercado, sectores o tu objetivo financiero.\nLa rotación busca aprovechar oportunidades y reducir riesgos.\n\n📊 *Tip:* Revisá tu cartera regularmente y ajustala según análisis y metas."},
    {"fecha": "28/11/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué significa si un activo está en 'modo riesgo ON'?\"\n\n🧠 *Respuesta Impulso Merval:*\n‘Modo riesgo ON’ indica que los inversores están más confiados y buscan activos con mayor riesgo y potencial de ganancia.\nEsto suele subir el precio de acciones, bonos y otros activos riesgosos.\n\n📊 *Tip:* En este modo, los activos seguros pueden bajar y los riesgos aumentan, así que ajustá tu cartera según tu perfil."},
    {"fecha": "05/12/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Por qué puede bajar una acciones cuando hay un buenos balances?\"\n\n🧠 *Respuesta Impulso Merval:*\nA veces las expectativas ya están reflejadas en el precio y un buen balance no sorprende porque incluso se esperaba uno mejor.\nOtras veces, la empresa puede advertir desafíos futuros (un balance proyectado malo).\n\n📊 *Tip:* No te fijes solo en el resultado, también analizá las proyecciones y compara el valor esperado por el mercado vs el valor recibido"},
    {"fecha": "12/12/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué significa cuando dicen ‘el mercado ya lo tenía priceado’?\"\n\n🧠 *Respuesta Impulso Merval:*\nSignifica que la información o evento ya estaba anticipado y reflejado en el precio de los activos.\nPor eso, cuando sucede, el precio no cambia mucho.\n\n📊 *Tip:* El mercado siempre intenta anticipar noticias para ajustar precios antes que ocurran."},
    {"fecha": "19/12/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Por qué las acciones bajan cuando sube la tasa de interés?\"\n\n🧠 *Respuesta Impulso Merval:*\nCuando suben las tasas, aumenta el costo de financiamiento para las empresas y disminuye el valor presente de sus ganancias futuras. Además, los inversores tienden a preferir activos más seguros como bonos, afectando la demanda de acciones.\n\n📊 *Tip:* Siempre mirá el contexto de tasas antes de tomar decisiones de inversión en renta variable."},
    {"fecha": "26/12/2025 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué es el riesgo país y por qué importa?\"\n\n🧠 *Respuesta Impulso Merval:*\nEl riesgo país mide la probabilidad de que un país no cumpla sus compromisos de deuda. Cuanto más alto, mayor el riesgo de default. Impacta en el costo de financiamiento y en el precio de bonos y acciones locales.\n\n📊 *Tip:* Seguí el riesgo país como un termómetro general de la confianza en la economía."},
    {"fecha": "02/01/2026 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué es el dólar contado con liquidación (CCL)?\"\n\n🧠 *Respuesta Impulso Merval:*\nEs una forma legal de comprar dólares en el mercado financiero mediante la compra-venta de activos. Sirve para dolarizarse sin restricciones, pero tiene costos y variaciones por oferta y demanda.\n\n📊 *Tip:* Es clave para quienes invierten en CEDEARs o buscan cobertura en dólares."},
    {"fecha": "09/01/2026 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué es una tasa nominal y una tasa efectiva?\"\n\n🧠 *Respuesta Impulso Merval:*\nLa tasa nominal es la que se informa sin considerar la capitalización. La tasa efectiva incluye el efecto de reinvertir los intereses. Cuanto más frecuente la capitalización, mayor la tasa efectiva.\n\n📊 *Tip:* Para comparar inversiones, siempre usá tasas efectivas."},
    {"fecha": "16/01/2026 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué diferencia hay entre un CEDEAR y una acción local?\"\n\n🧠 *Respuesta Impulso Merval:*\nEl CEDEAR representa acciones extranjeras pero cotiza en pesos, reflejando tanto la variación de la acción como del dólar CCL. Las acciones locales reflejan directamente empresas argentinas.\n\n📊 *Tip:* Los CEDEARs permiten diversificar internacionalmente desde Argentina."},
    {"fecha": "23/01/2026 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué es un ETF y por qué sirve para diversificar?\"\n\n🧠 *Respuesta Impulso Merval:*\nUn ETF es un fondo que replica un índice o sector y cotiza como una acción. Permite diversificación automática con una sola operación.\n\n📊 *Tip:* Ideal para armar carteras diversificadas internacionales desde plataformas habilitadas."},
    {"fecha": "30/01/2026 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué significa capitalizar intereses?\"\n\n🧠 *Respuesta Impulso Merval:*\nEs reinvertir los intereses generados, haciendo que el nuevo interés se calcule sobre un monto mayor. Es la base del interés compuesto.\n\n📊 *Tip:* Capitalizar intereses potencia el crecimiento a largo plazo."},
    {"fecha": "06/02/2026 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué es la inflación núcleo?\"\n\n🧠 *Respuesta Impulso Merval:*\nEs la inflación que excluye precios muy volátiles (como alimentos y energía). Se usa para medir la tendencia subyacente de los precios.\n\n📊 *Tip:* Es un dato que los bancos centrales miran para definir política monetaria."},
    {"fecha": "13/02/2026 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué es el spread cambiario?\"\n\n🧠 *Respuesta Impulso Merval:*\nEs la diferencia entre el precio de compra y venta de dólares. Un spread alto indica menor liquidez o mayor incertidumbre.\n\n📊 *Tip:* Afecta el costo de operar dólar MEP o CCL."},
    {"fecha": "20/02/2026 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué es el VIX o 'índice del miedo'?\"\n\n🧠 *Respuesta Impulso Merval:*\nEl VIX mide la volatilidad esperada en Wall Street. Cuando sube, refleja mayor incertidumbre en los mercados.\n\n📊 *Tip:* Aunque no impacta directamente en Argentina, da señales de riesgo global."},
    {"fecha": "27/02/2026 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué es un ADR?\"\n\n🧠 *Respuesta Impulso Merval:*\nEs un certificado que permite operar acciones extranjeras en la Bolsa de Nueva York. Algunos ADR son de empresas argentinas que cotizan afuera.\n\n📊 *Tip:* Sirven para invertir en el exterior sin operar directamente en mercados internacionales."},
    {"fecha": "06/03/2026 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué es el drawdown?\"\n\n🧠 *Respuesta Impulso Merval:*\nEs la caída máxima desde un pico de rentabilidad hasta un mínimo. Mide cuánto puede bajar una inversión antes de recuperarse.\n\n📊 *Tip:* Es un buen indicador para evaluar el riesgo real de una estrategia."},
    {"fecha": "13/03/2026 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué es un stop dinámico (trailing stop)?\"\n\n🧠 *Respuesta Impulso Merval:*\nEs un stop loss que se ajusta automáticamente si el precio sube, protegiendo ganancias pero limitando pérdidas.\n\n📊 *Tip:* Muy útil para automatizar salidas en tendencias alcistas."},
    {"fecha": "20/03/2026 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué son los rendimientos reales?\"\n\n🧠 *Respuesta Impulso Merval:*\nEs el rendimiento descontando la inflación. Si ganás 50% pero la inflación fue 40%, tu rendimiento real fue 10%.\n\n📊 *Tip:* Siempre analizá los rendimientos ajustados por inflación."},
    {"fecha": "27/03/2026 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué es la curva invertida de tasas?\"\n\n🧠 *Respuesta Impulso Merval:*\nCuando las tasas de corto plazo superan a las de largo plazo. Suele anticipar recesiones en EE.UU.\n\n📊 *Tip:* Aunque no es exacto, es una señal que los inversores globales miran de cerca."},
    {"fecha": "03/04/2026 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué significa 'mercado bajista'?\"\n\n🧠 *Respuesta Impulso Merval:*\nEs cuando un índice o activo cae más de 20% desde su máximo. Refleja pesimismo generalizado.\n\n📊 *Tip:* Los mercados bajistas también generan oportunidades si se invierte con prudencia."},
    {"fecha": "10/04/2026 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué es el rendimiento por dividendo?\"\n\n🧠 *Respuesta Impulso Merval:*\nEs el porcentaje que paga una acción en dividendos respecto a su precio actual.\n\n📊 *Tip:* Útil para comparar acciones de empresas maduras que reparten ganancias."},
    {"fecha": "17/04/2026 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué diferencia hay entre liquidez y solvencia?\"\n\n🧠 *Respuesta Impulso Merval:*\nLiquidez es la capacidad de pagar en el corto plazo. Solvencia es la capacidad de cumplir todas las deudas a largo plazo.\n\n📊 *Tip:* Ambos conceptos son clave al analizar empresas y bonos."},
    {"fecha": "24/04/2026 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué es el FCI Money Market?\"\n\n🧠 *Respuesta Impulso Merval:*\nEs un fondo común de inversión conservador, que invierte en plazos fijos y cauciones. Ideal para rendimientos diarios con bajo riesgo.\n\n📊 *Tip:* Es una buena opción para tener liquidez con algo de renta."},
    {"fecha": "01/05/2026 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué es un ratio precio/ganancia (P/E)?\"\n\n🧠 *Respuesta Impulso Merval:*\nMuestra cuántos años de ganancias actuales se necesitarían para recuperar el precio de la acción.\n\n📊 *Tip:* Sirve para comparar si una acción está cara o barata frente a su sector."},
    {"fecha": "08/05/2026 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Por qué conviene tener pesos en caución?\"\n\n🧠 *Respuesta Impulso Merval:*\nPorque rinde diariamente y permite aprovechar liquidez mientras no se usa para otras inversiones. Es bajo riesgo y flexible.\n\n📊 *Tip:* Es útil para estacionar pesos en espera de oportunidades."},
    {"fecha": "15/05/2026 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué es la tasa forward?\"\n\n🧠 *Respuesta Impulso Merval:*\nEs una tasa implícita que refleja las expectativas futuras de tasas de interés, derivada de los precios actuales de activos.\n\n📊 *Tip:* Es un dato útil para anticipar posibles movimientos de política monetaria."},
    {"fecha": "22/05/2026 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Por qué los CEDEARs pueden subir incluso si baja la acción afuera?\"\n\n🧠 *Respuesta Impulso Merval:*\nPorque además de la acción, el CEDEAR refleja el dólar CCL. Si el dólar sube fuerte en Argentina, puede compensar o superar la baja de la acción internacional.\n\n📊 *Tip:* Siempre mirá ambos factores: la acción en su mercado y el CCL."},
    {"fecha": "29/05/2026 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué es el costo de oportunidad?\"\n\n🧠 *Respuesta Impulso Merval:*\nEs lo que dejás de ganar al elegir una inversión sobre otra. Toda decisión de inversión tiene un costo de oportunidad implícito.\n\n📊 *Tip:* Siempre compará alternativas antes de decidir dónde poner el capital."},
    {"fecha": "05/06/2026 15:40", "mensaje": "📩 *Viernes de preguntas:*\n\"¿Qué es la prima de riesgo?\"\n\n🧠 *Respuesta Impulso Merval:*\nEs el extra de rendimiento que exige un inversor para asumir un riesgo mayor respecto a un activo seguro.\n\n📊 *Tip:* Cuanto mayor la prima de riesgo, más cuidado hay que tener con ese activo."},
    {"fecha": "17/06/2025 15:50", "mensaje": "💡 *Invertir es preparar el futuro, no adivinarlo.* Cada aporte hoy es un paso firme hacia tus metas."},
    {"fecha": "24/06/2025 15:50", "mensaje": "🔒 *La disciplina vence a la emoción.* Mantené el plan incluso cuando el mercado te tiente a desviarte."},
    {"fecha": "01/07/2025 15:50", "mensaje": "🌱 *El crecimiento es lento pero constante.* Como un árbol, tu cartera necesita tiempo para dar frutos."},
    {"fecha": "08/07/2025 15:50", "mensaje": "🧘‍♂️ *No dejes que el ruido del día a día opaque tu visión de largo plazo.* Paciencia y foco."},
    {"fecha": "15/07/2025 15:50", "mensaje": "🚀 *El mejor día para empezar fue ayer. El segundo mejor es hoy.* Seguimos construyendo 💪📈."},
    {"fecha": "22/07/2025 15:50", "mensaje": "🔎 *Las caídas son parte del camino.* Aprovechá las oportunidades mientras otros se paralizan."},
    {"fecha": "29/07/2025 15:50", "mensaje": "💪 *La paciencia es el mayor activo del inversor.* Las recompensas llegan para quien sabe esperar."},
    {"fecha": "05/08/2025 15:50", "mensaje": "🎯 *Competí solo con vos mismo:* ser más disciplinado, más constante, más paciente."},
    {"fecha": "12/08/2025 15:50", "mensaje": "📈 *No intentes predecir el mercado.* Creá un plan sólido y seguí el rumbo, pase lo que pase."},
    {"fecha": "19/08/2025 15:50", "mensaje": "⏳ *El tiempo es tu mejor aliado.* Nunca subestimes lo que podés lograr con constancia."},
    {"fecha": "26/08/2025 15:50", "mensaje": "⏳ *No intentes encontrar el momento perfecto.* El verdadero secreto está en *permanecer invertido*, no en acertar el timing."},
    {"fecha": "02/09/2025 15:50", "mensaje": "🔥 *La emoción es el enemigo del inversor.* Tomá decisiones racionales, no impulsivas."},
    {"fecha": "09/09/2025 15:50", "mensaje": "📊 *Las noticias del día no definen tus objetivos.* Pensá siempre en tu horizonte."},
    {"fecha": "16/09/2025 15:50", "mensaje": "🏗️ *Cada aporte suma.* Pequeñas decisiones diarias construyen grandes resultados futuros."},
    {"fecha": "23/09/2025 15:50", "mensaje": "💎 *La constancia genera riqueza.* Las ganancias extraordinarias son el resultado de lo ordinario bien hecho."},
    {"fecha": "30/09/2025 15:50", "mensaje": "📉 *Las correcciones no son el enemigo.* Son parte del ciclo normal del mercado."},
    {"fecha": "07/10/2025 15:50", "mensaje": "🧭 *Invertir es un camino, no una carrera.* La velocidad no importa, la dirección sí."},
    {"fecha": "14/10/2025 15:50", "mensaje": "💼 *La mejor estrategia es la que podés sostener en el tiempo.* Alineá tu cartera a tu perfil."},
    {"fecha": "21/10/2025 15:50", "mensaje": "🛡️ *Diversificar es proteger.* No pongas todos los huevos en la misma canasta."},
    {"fecha": "28/10/2025 15:50", "mensaje": "🔮 *Nadie puede adivinar el mercado todos los días.* Pero todos podemos tener un plan sólido."},
    {"fecha": "04/11/2025 15:50", "mensaje": "🎢 *El mercado sube y baja.* Tu plan debe estar preparado para ambos escenarios."},
    {"fecha": "11/11/2025 15:50", "mensaje": "🔗 *El mejor inversor es quien puede seguir su estrategia en momentos de incertidumbre.*"},
    {"fecha": "18/11/2025 15:50", "mensaje": "🧱 *Construir patrimonio es un proceso de años, no de semanas.* Pensá siempre a largo plazo."},
    {"fecha": "25/11/2025 15:50", "mensaje": "🌤️ *Luego de cada tormenta, vuelve la calma.* No te dejes dominar por el pánico."},
    {"fecha": "02/12/2025 15:50", "mensaje": "📚 *Invertir es aprender constantemente.* Cada experiencia, buena o mala, deja lecciones."},
    {"fecha": "09/12/2025 15:50", "mensaje": "🔑 *El secreto no está en ganarle al mercado cada día, sino en no salirte del plan en los momentos difíciles.*"},
    {"fecha": "16/12/2025 15:50", "mensaje": "📆 *Años de constancia superan días de brillantez.* Las grandes fortunas se construyen con paciencia."},
    {"fecha": "23/12/2025 15:50", "mensaje": "🎯 *Mantené el foco en tus metas, no en los ruidos del mercado.* Los objetivos mandan."},
    {"fecha": "30/12/2025 15:50", "mensaje": "🔄 *Revisá tu plan, no tu cartera todos los días.* El exceso de control genera ansiedad."},
    {"fecha": "06/01/2026 15:50", "mensaje": "🧮 *El interés compuesto necesita dos ingredientes:* tiempo y constancia. Dale ambos."},
    {"fecha": "13/01/2026 15:50", "mensaje": "🔔 *Los mejores inversores tienen estómago fuerte, no información privilegiada.* La clave es soportar la volatilidad."},
    {"fecha": "20/01/2026 15:50", "mensaje": "📌 *No esperes certezas para invertir.* Las oportunidades aparecen cuando otros dudan."},
    {"fecha": "27/01/2026 15:50", "mensaje": "🕰️ *Cada aporte de hoy es un año menos de trabajo futuro.* La libertad financiera se construye en el presente."},
    {"fecha": "03/02/2026 15:50", "mensaje": "⚠️ *El peor error es no estar invertido.* El segundo, es dejarse dominar por el miedo."},
    {"fecha": "10/02/2026 15:50", "mensaje": "📊 *Las caídas temporales son normales.* Los mercados suben a largo plazo porque las empresas crecen."},
    {"fecha": "17/02/2026 15:50", "mensaje": "🧭 *El plan es tu guía en medio del ruido.* Seguí el proceso, no las emociones."},
    {"fecha": "24/02/2026 15:50", "mensaje": "💸 *El dinero trabaja para vos cuando vos dormís.* Cada inversión es un empleado más a tu servicio."},
    {"fecha": "03/03/2026 15:50", "mensaje": "🎯 *Definí tus objetivos y actuá en consecuencia.* Sin rumbo, no hay llegada."},
    {"fecha": "10/03/2026 15:50", "mensaje": "📈 *No te obsesiones con el precio perfecto de entrada.* Lo importante es estar dentro."},
    {"fecha": "17/03/2026 15:50", "mensaje": "🏔️ *El camino del inversor tiene subidas y bajadas.* La vista panorámica solo se logra desde arriba, después de años."},
    {"fecha": "24/03/2026 15:50", "mensaje": "🔐 *Invertir es poner el dinero donde trabaja solo.* Dejá que el tiempo haga su magia."},
    {"fecha": "31/03/2026 15:50", "mensaje": "⚙️ *No te dejes llevar por modas del mercado.* El plan probado siempre supera la emoción pasajera."},
    {"fecha": "07/04/2026 15:50", "mensaje": "📊 *Controlá lo controlable: aportes, diversificación y paciencia.* El resto es ruido."},
    {"fecha": "14/04/2026 15:50", "mensaje": "🌄 *Cada crisis es también una oportunidad.* Quien sabe mantener la calma, suele salir fortalecido."},
    {"fecha": "21/04/2026 15:50", "mensaje": "📅 *Mirar el mercado todos los días no acelera el resultado.* Disfrutá el proceso."},
    {"fecha": "28/04/2026 15:50", "mensaje": "💵 *La libertad financiera es un maratón, no un sprint.* Cada mes cuenta."},
    {"fecha": "05/05/2026 15:50", "mensaje": "🔎 *No busques la próxima gran oportunidad.* Perfeccioná tu constancia."},
    {"fecha": "12/05/2026 15:50", "mensaje": "🧮 *Las rentabilidades extraordinarias surgen de lo ordinario hecho de forma consistente durante años.*"},
    {"fecha": "19/05/2026 15:50", "mensaje": "💼 *Invertir es comprarte tiempo en el futuro.* El capital trabaja mientras vos vivís."},
    {"fecha": "26/05/2026 15:50", "mensaje": "📊 *El mercado premia la paciencia, no la ansiedad.* Cada día invertido suma."},
    {"fecha": "02/06/2026 15:50", "mensaje": "⚖️ *El peor error es abandonar el plan por miedo.* Seguir es siempre más rentable que dudar."},
]

def cerrar_excel():
    os.system('taskkill /f /im excel.exe')

def enviar_mensaje(texto, grupo=None):
    destino = grupo if grupo else nombre_grupo
    print(f"🔔 Enviando mensaje a {destino}: {texto}")
    logging.info(f"Enviando mensaje a {destino}: {texto}") 

    pywhatkit.sendwhatmsg_to_group_instantly(destino, "", wait_time=10, tab_close=False)
    time.sleep(3)
    
    if texto == "[Resumen alertas 📊]":
        pyautogui.write(texto)
        pyautogui.press("enter")
        time.sleep(0.5)
        pyautogui.hotkey("ctrl", "v")
    else:
        pyperclip.copy(texto)
        pyautogui.hotkey("ctrl", "v")

    time.sleep(5)
    pyautogui.press("enter")
    time.sleep(5)
    pyautogui.hotkey("ctrl", "w")

    if texto == "[Resumen alertas 📊]":
        time.sleep(1)
        cerrar_excel()

print("Bot iniciado. Esperando el horario correcto...")
logging.info("Bot iniciado correctamente.")

while True:
    ahora = datetime.datetime.now()
    dia_actual = ahora.strftime("%A").lower()
    hora_actual = ahora.strftime("%H:%M")
    fecha_actual = ahora.strftime("%d/%m/%Y %H:%M")

    for item in mensajes_semana:
        if dia_actual in item["dias"] and hora_actual == item["hora"]:
            if item["mensaje"] == "cotizacion_dolar":
                mensaje_final = generar_cotizacion_dolar()
            elif item["mensaje"] == "noticia_mercado":
                mensaje_final = generar_mensaje_resumen()
            elif item["mensaje"] == "alerta_bursatil":
                mensaje_final = generar_alerta_aleatoria()
            elif item["mensaje"] == "alerta_bursatil_arg":
                mensaje_final = generar_alerta_aleatoria_arg()
            elif item["mensaje"] == "resumenAlertas":
                generar_resumen_alertas()
                seleccionar_y_copiar_excel()
                mensaje_final = "[Resumen alertas 📊]"
            else:
                mensaje_final = item["mensaje"]

            if "[!] Error" in mensaje_final:
                print(mensaje_final)
            else:
                grupo_destino = item.get("grupo", nombre_grupo)
                enviar_mensaje(mensaje_final, grupo=grupo_destino)

    # Logica de mensajes por fecha
    for item in mensajes_fecha:
        if fecha_actual == item["fecha"]:
            grupo_destino = item.get("grupo", nombre_grupo)
            enviar_mensaje(item["mensaje"], grupo=grupo_destino)

    segundos_restantes = 60 - ahora.second
    time.sleep(segundos_restantes)