from .mensajeCotizacionesDolar import generar_cotizacion_dolar
from .mensajeResumen import generar_noticia_mercado
from .mensajeAlertaCompra import generar_alerta_aleatoria
from .mensajeAlertaCompra import generar_alerta_aleatoria_arg